"""Context shared by the multilingual shell.

The UI dictionary is intentionally small and stable. Page-specific content can
move to Django gettext catalogs incrementally without coupling templates to the
legacy URL suffixes while the public routes use language-neutral names.
"""

from django.utils.translation import get_language


UI_TEXT = {
    'fa': {
        'home': 'صفحه اصلی',
        'datasets': 'دیتاست‌ها',
        'annotation': 'برچسب‌گذاری',
        'define_dataset': 'تعریف دیتاست',
        'viewer_title': 'نمایشگر داده', 'viewer_back': 'بازگشت به فایل‌ها', 'viewer_showing': 'نمایش', 'viewer_of': 'از', 'viewer_records': 'رکورد', 'viewer_error_title': 'نمایش داده امکان‌پذیر نیست',
        'workflow_new_title': 'تعریف / بارگذاری دیتاست جدید',
        'workflow_basic_title': 'تعریف دیتاست (روش پایه)',
        'workflow_basic_help': 'تعریف دیتاست جدید به همراه فیلدهای اطلاعاتی دیتاست',
        'workflow_advanced_title': 'تعریف دیتاست (روش پیشرفته)',
        'workflow_advanced_help': 'تعریف دیتاست جدید به همراه فرایند گمنام‌سازی',
        'workflow_start': 'شروع کنید',
        'workflow_define': 'تعریف دیتاست',
        'workflow_columns': 'افزودن نام و نوع ستون‌ها',
        'workflow_review_columns': 'نمایش و تأیید اطلاعات ستون‌ها',
        'workflow_submit': 'تأیید نهایی و ارسال',
        'workflow_upload_file': 'بارگذاری فایل دیتاست',
        'workflow_choose_anonymization': 'انتخاب روش گمنام‌سازی',
        'workflow_anonymize': 'گمنام‌سازی دیتاست',
        'workflow_anonymize_help': 'روش‌های انتخاب‌شده را تأیید کنید، سپس پیش‌نمایش پاک‌سازی‌شده را به‌صورت محلی ایجاد کنید.',
        'workflow_preview': 'نمایش دیتاست گمنام‌سازی‌شده',
        'workflow_confirmation': 'تأیید نهایی',
        'workflow_name': 'عنوان دیتاست',
        'workflow_owner': 'مالک دیتاست',
        'workflow_language': 'زبان',
        'workflow_license': 'مجوز استفاده',
        'workflow_format': 'قالب داده',
        'workflow_records': 'تعداد نمونه‌های دیتاست',
        'workflow_price': 'قیمت دیتاست (تومان)',
        'workflow_approval': 'خریدار قبل از دریافت یا خرید به تأیید من نیاز دارد',
        'workflow_description': 'توضیحات',
        'workflow_tags': 'برچسب‌ها (برای معرفی و جستجوی دیتاست)',
        'workflow_add_tag': 'افزودن برچسب',
        'workflow_tags_help': 'برای پیدا کردن آسان‌تر دیتاست، برچسب‌های توصیفی اضافه کنید.',
        'workflow_file': 'انتخاب فایل',
        'workflow_previous': 'قبلی',
        'workflow_next': 'بعدی',
        'workflow_add_column': 'افزودن ستون جدید',
        'workflow_save_changes': 'ذخیره تغییرات',
        'workflow_column_name': 'عنوان ستون',
        'workflow_data_type': 'نوع داده',
        'workflow_anonymization_method': 'روش گمنام‌سازی',
        'workflow_anonymize_action': 'گمنام‌سازی',
        'workflow_consent_title': 'رضایت‌نامه ارسال داده‌ها به پلتفرم',
        'workflow_consent_intro': 'قبل از ارسال هرگونه داده به پلتفرم، لطفاً شرایط و ضوابط زیر را مطالعه کنید.',
        'workflow_consent_body': 'با ارسال داده‌ها تأیید می‌کنید که مالک قانونی آن‌ها هستید و با استفاده از داده‌ها در چارچوب اهداف پلتفرم موافقید.',
        'workflow_consent_agree': 'موافقت می‌کنم',
        'workflow_send': 'ارسال',
        'workflow_waiting': 'منتظر شروع ...',
        'workflow_verify': 'لطفاً تأیید ارسال را فعال کنید.',
        'workflow_choose_file': 'لطفاً یک فایل انتخاب کنید.',
        'workflow_upload_failed': 'بارگذاری ناموفق بود.',
        'workflow_upload_complete': 'فایل و اطلاعات با موفقیت ذخیره شد.',
        'workflow_uploading': 'در حال بارگذاری ...',
        'workflow_upload_starting': 'شروع بارگذاری ...',
        'workflow_lang_en': 'انگلیسی', 'workflow_lang_fa': 'فارسی', 'workflow_lang_ar': 'عربی',
        'workflow_format_text': 'متن', 'workflow_format_image': 'تصویر', 'workflow_format_sound': 'صوت',
        'workflow_no': 'خیر', 'workflow_yes': 'بله', 'workflow_number': 'عدد',
        'workflow_stage_basics': 'اطلاعات پایه', 'workflow_stage_files': 'فایل‌ها', 'workflow_stage_transfer': 'بارگذاری', 'workflow_stage_inspect': 'بازبینی', 'workflow_stage_access': 'دسترسی و انتشار',
        'quality_report': 'گزارش کیفیت', 'quality_status': 'وضعیت پردازش', 'quality_score': 'امتیاز کیفیت', 'quality_assets': 'دارایی‌های بررسی‌شده', 'quality_findings': 'یافته‌ها', 'quality_publish': 'تأیید و انتشار', 'quality_publish_help': 'پس از بررسی گزارش، این نسخه را منتشر کنید.', 'quality_processing': 'در حال پردازش', 'quality_review': 'نیازمند بررسی', 'quality_failed': 'رد شده', 'quality_image_count': 'تعداد تصاویر', 'quality_corrupt': 'تصاویر خراب', 'quality_duplicates': 'تصاویر تکراری', 'quality_normalized': 'خروجی نرمال‌شده',
        'workflow_basics_help': 'اطلاعات دیتاست را یک‌بار وارد کنید؛ این اطلاعات به همه فایل‌ها متصل می‌ماند.', 'workflow_files_help': 'فایل منفرد، چند فایل، پوشه یا آرشیو فشرده تصاویر را اضافه کنید.', 'workflow_transfer_help': 'فایل‌ها به‌صورت قطعه‌ای و قابل ادامه بارگذاری می‌شوند.', 'workflow_inspect_help': 'فهرست فایل‌ها را بررسی کنید و منتظر کنترل کیفیت خودکار بمانید.', 'workflow_access_help': 'دسترسی بازار را انتخاب و مالکیت داده را تأیید کنید.',
        'workflow_choose_files': 'انتخاب فایل‌ها', 'workflow_choose_folder': 'انتخاب پوشه', 'workflow_selected_files': 'فایل‌های انتخاب‌شده', 'workflow_total_size': 'حجم کل', 'workflow_remove': 'حذف', 'workflow_start_upload': 'شروع بارگذاری', 'workflow_upload_queue': 'صف بارگذاری', 'workflow_archive': 'آرشیو فشرده', 'workflow_file_manifest': 'فهرست فایل‌ها', 'workflow_inspection_pending': 'پس از بارگذاری همه فایل‌ها، بازبینی آغاز می‌شود.', 'workflow_access_title': 'دسترسی و انتشار', 'workflow_publish_note': 'تا پایان کنترل‌های خودکار، دیتاست قرنطینه خواهد بود.', 'workflow_choose_files_first': 'حداقل یک فایل یا پوشه انتخاب کنید.', 'workflow_upload_started': 'بارگذاری آغاز شد', 'workflow_upload_batch_complete': 'همه فایل‌ها بارگذاری شدند؛ کنترل کیفیت در حال پردازش است.', 'workflow_load_file_help': 'یک فایل ساختاریافته CSV، TSV یا Excel انتخاب کنید. پروفایل‌سازی پیش از بارگذاری، در مرورگر شما انجام می‌شود.', 'workflow_file_formats': 'CSV/TSV و Excel تا حجم ۵۰ مگابایت', 'workflow_local_profile': 'پروفایل‌سازی محلی', 'workflow_policy_help': 'نوع تشخیص‌داده‌شده را بررسی و برای هر ستون روش حفاظت را انتخاب کنید. ستون‌های شناسایی‌کننده نباید بدون حفاظت بمانند.', 'workflow_privacy_policy_help': 'موجودیت‌های متنی پوشانده می‌شوند؛ اعداد گرد یا بازه‌بندی و تاریخ‌ها به سال تبدیل می‌شوند.', 'workflow_preview_help': 'نمونه تبدیل‌شده را پیش از بارگذاری بررسی کنید. فایل اصلی از مرورگر شما ارسال نمی‌شود.', 'workflow_confirmation_help': 'تنظیمات دسترسی را بررسی و پیش از بارگذاری دیتاست پاک‌سازی‌شده، مالکیت داده را تأیید کنید.', 'workflow_calculated_from_file': 'محاسبه‌شده از فایل', 'workflow_sanitized_csv': 'CSV پاک‌سازی‌شده', 'workflow_changes_saved': 'روش‌های حفاظت ستون‌ها با موفقیت ذخیره شد.', 'workflow_deidentification_complete': 'گمنام‌سازی با موفقیت انجام شد. پیش‌نمایش را بررسی کنید.',
        'workflow_none': 'بدون گمنام‌سازی', 'workflow_ner': 'تشخیص موجودیت (NER)', 'workflow_round': 'گرد کردن عدد', 'workflow_bin': 'بازه‌بندی عدد', 'workflow_year': 'نگه‌داشتن سال', 'workflow_mask': 'جایگزینی با توکن', 'workflow_privacy_warning': 'برای ستون حساس باید روش حفاظت انتخاب شود.', 'workflow_transform_summary': 'تبدیل انجام شد', 'workflow_residual_pii': 'ممکن است اطلاعات شخصی باقی مانده باشد؛ پیش از انتشار بررسی کنید.', 'workflow_no_residual_pii': 'سیگنال رایج اطلاعات شخصی در نمونه پیدا نشد.', 'workflow_file_too_large': 'این فرایند محلی برای فایل‌های حداکثر ۵۰ مگابایت است.', 'workflow_excel_unavailable': 'پشتیبانی Excel در دسترس نیست؛ فایل CSV انتخاب کنید.', 'workflow_profile_failed': 'پروفایل فایل ساخته نشد.', 'workflow_deidentification_required': 'ابتدا پیش‌نمایش گمنام‌سازی را اجرا کنید.', 'workflow_anonymization': 'روش حفاظت از حریم خصوصی', 'workflow_confidence': 'اطمینان تشخیص', 'workflow_data_type': 'نوع داده',
        'workflow_mean': 'میانگین', 'workflow_median': 'میانه', 'workflow_min': 'کمینه', 'workflow_max': 'بیشینه',
        'workflow_export': 'خروجی CSV', 'workflow_select_all': 'انتخاب همه', 'workflow_select_none': 'لغو انتخاب', 'workflow_no_rows': 'فایل داده‌ای برای نمایش ندارد.',
        'team': 'تیم ما',
        'faq': 'سؤالات متداول',
        'contact': 'ارتباط با ما',
        'login_register': 'ورود / ثبت‌نام',
        'profile': 'پروفایل من',
        'account': 'حساب کاربری',
        'my_datasets': 'دیتاست‌های من',
        'my_products': 'محصولات من',
        'requests': 'مدیریت درخواست‌ها',
        'logout': 'خروج از حساب',
        'language': 'زبان',
        'search_datasets': 'جستجوی دیتاست',
        'search_help': 'دیتاست موردنظر خود را با جستجوی کلمات کلیدی بیابید',
        'search_placeholder': 'عبارت جستجو را وارد نمایید',
        'unknown_publisher': 'ناشر نامشخص',
        'created': 'تاریخ ایجاد',
        'records': 'تعداد رکورد',
        'free': 'رایگان',
        'currency': 'تومان',
        'view_dataset': 'مشاهده دیتاست',
        'no_datasets': 'دیتاستی پیدا نشد',
        'change_search': 'عبارت جستجو را تغییر دهید یا بعداً دوباره تلاش کنید.',
        'description': 'توضیحات',
        'structure': 'ساختار دیتاست',
        'comments': 'نظرات کاربران',
        'technical_details': 'مشخصات فنی',
        'related_products': 'محصولات مرتبط',
        'likes': 'لایک‌ها',
        'files': 'تعداد فایل',
        'size': 'حجم',
        'no_description': 'هیچ توضیحی برای این مجموعه داده وجود ندارد',
        'no_structure': 'هیچ اطلاعاتی درباره ساختار داده‌ها موجود نیست',
        'no_comments': 'هنوز نظری ثبت نشده است',
        'download_dataset': 'دریافت/خرید دیتاست',
        'request_dataset': 'ثبت درخواست دریافت/خرید',
        'like_action': 'لایک',
        'share': 'اشتراک‌گذاری', 'share_telegram': 'تلگرام', 'share_whatsapp': 'واتس‌اپ', 'share_twitter': 'توییتر', 'copy_link': 'کپی لینک', 'link_copied': 'لینک با موفقیت کپی شد.', 'link_copy_failed': 'کپی لینک انجام نشد؛ لینک را دستی کپی کنید.',
        'view_metadata': 'نمایش اطلاعات توصیفی',
        'similar': 'دیتاست‌های مشابه',
        'papers': 'مقالات',
        'models': 'مدل‌ها',
        'services': 'سرویس‌ها',
        'comment_placeholder': 'نظر خود را اینجا بنویسید...',
        'send_comment': 'ارسال نظر',
        'reference_link': 'لینک مرجع',
        'format': 'فرمت',
        'language_label': 'زبان',
        'license': 'لایسنس',
        'platform_tagline': 'بازار حرفه‌ای تبادل و کشف داده',
        'platform_intro': 'دیتاست‌ها را پیدا کنید، به اشتراک بگذارید و با جامعه داده همکاری کنید.',
        'browse_datasets': 'مشاهده دیتاست‌ها',
        'get_started': 'شروع کنید',
        'dataset_count': 'دیتاست ثبت‌شده',
        'user_count': 'کاربر فعال',
        'request_count': 'درخواست پذیرفته‌شده',
        'footer_provided_by': 'ارائه‌شده توسط',
        'home_eyebrow': 'زیرساخت داده برای کار واقعی',
        'home_title': 'دنیای بدون مرز داده‌ها',
        'home_intro': 'مخزن ذخیره‌سازی، مبادله و اشتراک‌گذاری داده‌ها ویژه کاربران حوزه هوش مصنوعی',
        'home_primary': 'مشاهده دیتاست‌ها',
        'home_secondary': 'افزودن دیتاست',
        'home_trust': 'یک مسیر روشن برای داده‌های قابل استفاده',
        'home_nav_workflow': 'روند کار',
        'home_nav_integrations': 'اتصال‌ها',
        'home_nav_start': 'شروع کار',
        'home_workflow_eyebrow': 'چطور کار می‌کند',
        'home_workflow_title': 'از فایل خام تا دیتاست قابل اعتماد',
        'home_workflow_intro': 'همه مراحل در یک جریان ساده و قابل پیگیری؛ بدون ابزارهای پراکنده و حدس‌زدن وضعیت پردازش.',
        'home_step_1': 'کشف یا افزودن',
        'home_step_1_text': 'از مخزن DataHub جستجو کنید یا فایل‌ها و پوشه‌های خود را اضافه کنید.',
        'home_step_2': 'توضیح و حفاظت',
        'home_step_2_text': 'متادیتا، برچسب‌ها و روش‌های گمنام‌سازی را پیش از بارگذاری بررسی کنید.',
        'home_step_3': 'کنترل کیفیت',
        'home_step_3_text': 'ساختار فایل، نمونه داده و نشانه‌های اطلاعات شخصی به‌صورت خودکار بررسی می‌شود.',
        'home_step_4': 'انتشار و تبادل',
        'home_step_4_text': 'پس از تأیید، دیتاست را خصوصی، رایگان یا قابل خرید در بازارچه منتشر کنید.',
        'home_capabilities_eyebrow': 'ساخته‌شده برای تیم‌های داده',
        'home_capabilities_title': 'هر چیزی که برای یک دیتاست حرفه‌ای لازم است',
        'home_capabilities_intro': 'از اولین فایل تا نسخه نهایی، اطلاعات، فایل‌ها و وضعیت هر دیتاست در یکجا می‌ماند.',
        'home_capability_discover': 'کشف سریع',
        'home_capability_discover_text': 'با جستجوی متادیتا و برچسب‌ها، دیتاست مناسب پروژه را سریع‌تر پیدا کنید.',
        'home_capability_prepare': 'آماده‌سازی امن',
        'home_capability_prepare_text': 'فایل‌های بزرگ، آرشیوها و داده‌های ساختاریافته را با پردازش قابل پیگیری آماده کنید.',
        'home_capability_exchange': 'بازارچه داده',
        'home_capability_exchange_text': 'دسترسی، قیمت و شرایط استفاده را کنترل کنید و داده را با دیگران مبادله کنید.',
        'home_integrations_title': 'اتصال به منابع مورد اعتماد',
        'home_integrations_text': 'متادیتای دیتاست‌های Hugging Face و Kaggle را دریافت کنید و در DataHub مدیریت کنید.',
        'home_privacy_title': 'حریم خصوصی از ابتدا در جریان کار',
        'home_privacy_text': 'پروفایل‌سازی محلی، شناسایی ستون‌های حساس و کنترل کیفیت کمک می‌کند قبل از انتشار تصمیم مطمئن‌تری بگیرید.',
        'home_privacy_action': 'شروع آماده‌سازی دیتاست',
        'home_faq_eyebrow': 'راهنما',
        'home_faq_title': 'پرسش‌های متداول',
        'home_faq_intro': 'پاسخ کوتاه به مهم‌ترین پرسش‌ها برای شروع کار با DataHub.',
        'home_faq_q1': 'چه نوع فایل‌هایی را می‌توانم اضافه کنم؟',
        'home_faq_a1': 'فایل منفرد، چند فایل، پوشه و آرشیوهای فشرده مانند ZIP را می‌توانید اضافه کنید.',
        'home_faq_q2': 'آیا داده پیش از انتشار بررسی می‌شود؟',
        'home_faq_a2': 'بله. کنترل کیفیت، ساختار فایل و نشانه‌های اطلاعات شخصی بررسی می‌شوند و نتیجه برای بازبینی شما ثبت می‌شود.',
        'home_faq_q3': 'آیا می‌توانم از Kaggle یا Hugging Face وارد کنم؟',
        'home_faq_a3': 'بله. شناسه دیتاست را وارد کنید تا متادیتا و فایل‌ها از مسیر اتصال امن پلتفرم دریافت شوند.',
        'home_faq_q4': 'چه زمانی دیتاست برای دیگران قابل مشاهده است؟',
        'home_faq_a4': 'تا زمان تأیید و انتشار، دیتاست در وضعیت قرنطینه یا پیش‌نویس می‌ماند و عمومی نمی‌شود.',
        'home_cta_title': 'داده بعدی پروژه‌تان را آماده کنید',
        'home_cta_text': 'همین حالا دیتاست‌های موجود را ببینید یا اولین دیتاست خود را به DataHub اضافه کنید.',
        'home_cta_action': 'شروع کنید',
    },
    'en': {
        'home': 'Home',
        'datasets': 'Datasets',
        'annotation': 'Annotation',
        'define_dataset': 'Create dataset',
        'viewer_title': 'Data viewer', 'viewer_back': 'Back to files', 'viewer_showing': 'Showing', 'viewer_of': 'of', 'viewer_records': 'records', 'viewer_error_title': 'The data could not be displayed',
        'workflow_new_title': 'Create or upload a dataset',
        'workflow_basic_title': 'Create dataset (basic)',
        'workflow_basic_help': 'Define a dataset and its metadata fields',
        'workflow_advanced_title': 'Create dataset (advanced)',
        'workflow_advanced_help': 'Define a dataset with an anonymization workflow',
        'workflow_start': 'Get started',
        'workflow_define': 'Define dataset',
        'workflow_columns': 'Add column names and types',
        'workflow_review_columns': 'Review and confirm column metadata',
        'workflow_submit': 'Final confirmation and submit',
        'workflow_upload_file': 'Upload dataset file',
        'workflow_choose_anonymization': 'Choose anonymization method',
        'workflow_anonymize': 'Anonymize dataset',
        'workflow_anonymize_help': 'Confirm the selected methods, then generate the sanitized preview locally.',
        'workflow_preview': 'Preview anonymized dataset',
        'workflow_confirmation': 'Final confirmation',
        'workflow_name': 'Dataset name',
        'workflow_owner': 'Dataset owner',
        'workflow_language': 'Language',
        'workflow_license': 'License',
        'workflow_format': 'Data format',
        'workflow_records': 'Number of records',
        'workflow_price': 'Dataset price (toman)',
        'workflow_approval': 'Require my approval before a buyer downloads or purchases',
        'workflow_description': 'Description',
        'workflow_tags': 'Tags (used to discover and search this dataset)',
        'workflow_add_tag': 'Add tag',
        'workflow_tags_help': 'Add descriptive tags to make your dataset easier to find.',
        'workflow_file': 'Choose file',
        'workflow_previous': 'Back',
        'workflow_next': 'Next',
        'workflow_add_column': 'Add column',
        'workflow_save_changes': 'Save changes',
        'workflow_column_name': 'Column name',
        'workflow_data_type': 'Data type',
        'workflow_anonymization_method': 'Anonymization method',
        'workflow_anonymize_action': 'Anonymize',
        'workflow_consent_title': 'Consent to submit data',
        'workflow_consent_intro': 'Please review these terms before submitting any data to the platform.',
        'workflow_consent_body': 'By submitting data, you confirm that you own it and agree to its use within the platform goals.',
        'workflow_consent_agree': 'I agree',
        'workflow_send': 'Submit',
        'workflow_waiting': 'Waiting to start ...',
        'workflow_verify': 'Please confirm that you agree to submit the dataset.',
        'workflow_choose_file': 'Please choose a file.',
        'workflow_upload_failed': 'Upload failed.',
        'workflow_upload_complete': 'File and metadata were saved successfully.',
        'workflow_uploading': 'Uploading ...',
        'workflow_upload_starting': 'Starting upload ...',
        'workflow_lang_en': 'English', 'workflow_lang_fa': 'Persian', 'workflow_lang_ar': 'Arabic',
        'workflow_format_text': 'Text', 'workflow_format_image': 'Image', 'workflow_format_sound': 'Audio',
        'workflow_no': 'No', 'workflow_yes': 'Yes', 'workflow_number': 'Number',
        'workflow_stage_basics': 'Basics', 'workflow_stage_files': 'Files', 'workflow_stage_transfer': 'Transfer', 'workflow_stage_inspect': 'Inspect', 'workflow_stage_access': 'Access & publish',
        'quality_report': 'Quality report', 'quality_status': 'Processing status', 'quality_score': 'Quality score', 'quality_assets': 'Inspected assets', 'quality_findings': 'Findings', 'quality_publish': 'Approve and publish', 'quality_publish_help': 'Review the report before publishing this version.', 'quality_processing': 'Processing', 'quality_review': 'Needs review', 'quality_failed': 'Failed', 'quality_image_count': 'Images', 'quality_corrupt': 'Corrupt images', 'quality_duplicates': 'Duplicate images', 'quality_normalized': 'Normalized output',
        'workflow_basics_help': 'Describe your dataset once; these details stay attached to every uploaded file.', 'workflow_files_help': 'Add individual files, many files, a folder, or a compressed image archive.', 'workflow_transfer_help': 'Uploads are chunked and resumable so large files do not need to restart.', 'workflow_inspect_help': 'Review the file manifest and wait for automated quality checks.', 'workflow_access_help': 'Choose marketplace access and confirm ownership before publishing.',
        'workflow_choose_files': 'Choose files', 'workflow_choose_folder': 'Choose folder', 'workflow_selected_files': 'Selected files', 'workflow_total_size': 'Total size', 'workflow_remove': 'Remove', 'workflow_start_upload': 'Start upload', 'workflow_upload_queue': 'Upload queue', 'workflow_archive': 'Compressed archive', 'workflow_file_manifest': 'File manifest', 'workflow_inspection_pending': 'Inspection starts after all files finish uploading.', 'workflow_access_title': 'Access and publication', 'workflow_publish_note': 'Your dataset will be quarantined until automated checks complete.', 'workflow_choose_files_first': 'Choose at least one file or folder.', 'workflow_upload_started': 'Upload started', 'workflow_upload_batch_complete': 'All files uploaded; quality checks are processing.', 'workflow_load_file_help': 'Select a structured CSV, TSV, or Excel file. Profiling runs locally in your browser before upload.', 'workflow_file_formats': 'CSV/TSV and Excel files up to 50 MB', 'workflow_local_profile': 'Local profile', 'workflow_policy_help': 'Review the detected type and choose a privacy action for each column. Sensitive identifier columns must not remain unprotected.', 'workflow_privacy_policy_help': 'Text entities are masked; numeric values can be rounded or grouped, and dates can be reduced to year.', 'workflow_preview_help': 'Inspect the transformed sample before upload. The original local file is never sent.', 'workflow_confirmation_help': 'Review access settings and confirm ownership before uploading the sanitized dataset.', 'workflow_calculated_from_file': 'Calculated from file', 'workflow_sanitized_csv': 'Sanitized CSV', 'workflow_changes_saved': 'Column privacy methods were saved successfully.', 'workflow_deidentification_complete': 'De-identification completed successfully. Review the preview.',
        'workflow_none': 'None', 'workflow_ner': 'Named entity recognition (NER)', 'workflow_round': 'Round values', 'workflow_bin': 'Group into ranges', 'workflow_year': 'Keep year only', 'workflow_mask': 'Replace with a token', 'workflow_privacy_warning': 'A protection method is required for sensitive columns.', 'workflow_transform_summary': 'Transformation complete', 'workflow_residual_pii': 'Possible residual personal data was detected; review before publishing.', 'workflow_no_residual_pii': 'No common personal-data signal was found in the sample.', 'workflow_file_too_large': 'This local workflow supports files up to 50 MB.', 'workflow_excel_unavailable': 'Excel support is unavailable; choose a CSV file.', 'workflow_profile_failed': 'Could not profile this file.', 'workflow_deidentification_required': 'Run the de-identification preview first.', 'workflow_anonymization': 'Privacy action', 'workflow_confidence': 'Detection confidence', 'workflow_data_type': 'Data type',
        'workflow_mean': 'Mean', 'workflow_median': 'Median', 'workflow_min': 'Minimum', 'workflow_max': 'Maximum',
        'workflow_export': 'Export CSV', 'workflow_select_all': 'Select all', 'workflow_select_none': 'Select none', 'workflow_no_rows': 'The selected file has no data rows.',
        'team': 'Our team',
        'faq': 'FAQ',
        'contact': 'Contact us',
        'login_register': 'Sign in / Register',
        'profile': 'My profile',
        'account': 'Account',
        'my_datasets': 'My datasets',
        'my_products': 'My products',
        'requests': 'Manage requests',
        'logout': 'Sign out',
        'language': 'Language',
        'search_datasets': 'Search datasets',
        'search_help': 'Find the dataset you need by searching keywords',
        'search_placeholder': 'Enter a search term',
        'unknown_publisher': 'Unknown publisher',
        'created': 'Created',
        'records': 'Records',
        'free': 'Free',
        'currency': 'Toman',
        'view_dataset': 'View dataset',
        'no_datasets': 'No datasets found',
        'change_search': 'Try changing your search terms or come back later.',
        'description': 'Description',
        'structure': 'Dataset structure',
        'comments': 'User comments',
        'technical_details': 'Technical details',
        'related_products': 'Related products',
        'likes': 'Likes',
        'files': 'Files',
        'size': 'Size',
        'no_description': 'No description is available for this dataset.',
        'no_structure': 'No structural information is available.',
        'no_comments': 'No comments yet.',
        'download_dataset': 'Download / purchase dataset',
        'request_dataset': 'Request access / purchase',
        'like_action': 'Like',
        'share': 'Share', 'share_telegram': 'Telegram', 'share_whatsapp': 'WhatsApp', 'share_twitter': 'X / Twitter', 'copy_link': 'Copy link', 'link_copied': 'Link copied successfully.', 'link_copy_failed': 'Could not copy the link. Please copy it manually.',
        'view_metadata': 'View metadata',
        'similar': 'Similar datasets',
        'papers': 'Papers',
        'models': 'Models',
        'services': 'Services',
        'comment_placeholder': 'Write a comment...',
        'send_comment': 'Post comment',
        'reference_link': 'Reference link',
        'format': 'Format',
        'language_label': 'Language',
        'license': 'License',
        'platform_tagline': 'A professional marketplace for data discovery and exchange',
        'platform_intro': 'Find datasets, share your work, and collaborate with the data community.',
        'browse_datasets': 'Browse datasets',
        'get_started': 'Get started',
        'dataset_count': 'Datasets',
        'user_count': 'Active users',
        'request_count': 'Approved requests',
        'footer_provided_by': 'Provided by',
        'home_eyebrow': 'Data infrastructure for real work',
        'home_title': 'A World of Data Without Borders',
        'home_intro': 'A data repository for storing, exchanging, and sharing datasets, built for AI professionals.',
        'home_primary': 'Browse datasets',
        'home_secondary': 'Add a dataset',
        'home_trust': 'One clear path to usable data',
        'home_nav_workflow': 'How it works',
        'home_nav_integrations': 'Integrations',
        'home_nav_start': 'Get started',
        'home_workflow_eyebrow': 'How it works',
        'home_workflow_title': 'From raw files to a trusted dataset',
        'home_workflow_intro': 'Keep every step in one visible workflow instead of stitching together scattered tools.',
        'home_step_1': 'Discover or add',
        'home_step_1_text': 'Search the DataHub catalog or add your own files and folders.',
        'home_step_2': 'Describe and protect',
        'home_step_2_text': 'Review metadata, tags, and privacy actions before upload.',
        'home_step_3': 'Run quality checks',
        'home_step_3_text': 'Inspect file structure, samples, and personal-data signals automatically.',
        'home_step_4': 'Publish and exchange',
        'home_step_4_text': 'After review, share a dataset privately, for free, or through the marketplace.',
        'home_capabilities_eyebrow': 'Built for data teams',
        'home_capabilities_title': 'Everything a professional dataset needs',
        'home_capabilities_intro': 'Keep metadata, files, and processing status together from the first upload to the final version.',
        'home_capability_discover': 'Fast discovery',
        'home_capability_discover_text': 'Use metadata and tags to find the right dataset for your project faster.',
        'home_capability_prepare': 'Safer preparation',
        'home_capability_prepare_text': 'Prepare large files, archives, and structured data with visible progress and checks.',
        'home_capability_exchange': 'Data marketplace',
        'home_capability_exchange_text': 'Control access, pricing, and terms while you exchange data with others.',
        'home_integrations_title': 'Connect trusted sources',
        'home_integrations_text': 'Bring Hugging Face and Kaggle dataset metadata into DataHub and manage it in one place.',
        'home_privacy_title': 'Privacy is part of the workflow',
        'home_privacy_text': 'Local profiling, sensitive-column detection, and quality checks help you make a confident decision before publishing.',
        'home_privacy_action': 'Prepare a dataset',
        'home_faq_eyebrow': 'Guide',
        'home_faq_title': 'Frequently asked questions',
        'home_faq_intro': 'Short answers to help you start using DataHub.',
        'home_faq_q1': 'What file types can I add?',
        'home_faq_a1': 'You can add one file, many files, a folder, or compressed archives such as ZIP files.',
        'home_faq_q2': 'Is data checked before it is published?',
        'home_faq_a2': 'Yes. Quality, file structure, and personal-data signals are checked and recorded for your review.',
        'home_faq_q3': 'Can I import from Kaggle or Hugging Face?',
        'home_faq_a3': 'Yes. Enter a dataset ID and the platform connector will retrieve metadata and files securely.',
        'home_faq_q4': 'When can other users see my dataset?',
        'home_faq_a4': 'A dataset stays in draft or quarantine until you review and publish it.',
        'home_cta_title': 'Prepare your next project dataset',
        'home_cta_text': 'Browse what is available or add your first dataset to DataHub today.',
        'home_cta_action': 'Get started',
    },
    'ar': {
        'home': 'الرئيسية',
        'datasets': 'مجموعات البيانات',
        'annotation': 'التوسيم',
        'define_dataset': 'إنشاء مجموعة بيانات',
        'viewer_title': 'عارض البيانات', 'viewer_back': 'العودة إلى الملفات', 'viewer_showing': 'عرض', 'viewer_of': 'من', 'viewer_records': 'سجلاً', 'viewer_error_title': 'تعذر عرض البيانات',
        'workflow_new_title': 'إنشاء أو تحميل مجموعة بيانات',
        'workflow_basic_title': 'إنشاء مجموعة بيانات (أساسي)',
        'workflow_basic_help': 'تعريف مجموعة البيانات وحقولها الوصفية',
        'workflow_advanced_title': 'إنشاء مجموعة بيانات (متقدم)',
        'workflow_advanced_help': 'تعريف مجموعة البيانات مع سير عمل لإخفاء الهوية',
        'workflow_start': 'ابدأ الآن',
        'workflow_define': 'تعريف مجموعة البيانات',
        'workflow_columns': 'إضافة أسماء وأنواع الأعمدة',
        'workflow_review_columns': 'مراجعة بيانات الأعمدة وتأكيدها',
        'workflow_submit': 'التأكيد النهائي والإرسال',
        'workflow_upload_file': 'تحميل ملف مجموعة البيانات',
        'workflow_choose_anonymization': 'اختيار طريقة إخفاء الهوية',
        'workflow_anonymize': 'إخفاء هوية مجموعة البيانات',
        'workflow_anonymize_help': 'أكد الأساليب المحددة، ثم أنشئ المعاينة المنقّحة محليًا.',
        'workflow_preview': 'معاينة مجموعة البيانات المجهولة',
        'workflow_confirmation': 'التأكيد النهائي',
        'workflow_name': 'اسم مجموعة البيانات',
        'workflow_owner': 'مالك مجموعة البيانات',
        'workflow_language': 'اللغة',
        'workflow_license': 'الترخيص',
        'workflow_format': 'تنسيق البيانات',
        'workflow_records': 'عدد السجلات',
        'workflow_price': 'سعر مجموعة البيانات (تومان)',
        'workflow_approval': 'طلب موافقتي قبل التنزيل أو الشراء',
        'workflow_description': 'الوصف',
        'workflow_tags': 'الوسوم (لاكتشاف مجموعة البيانات والبحث عنها)',
        'workflow_add_tag': 'إضافة وسم',
        'workflow_tags_help': 'أضف وسوماً وصفية لتسهيل العثور على مجموعة البيانات.',
        'workflow_file': 'اختيار ملف',
        'workflow_previous': 'السابق',
        'workflow_next': 'التالي',
        'workflow_add_column': 'إضافة عمود',
        'workflow_save_changes': 'حفظ التغييرات',
        'workflow_column_name': 'اسم العمود',
        'workflow_data_type': 'نوع البيانات',
        'workflow_anonymization_method': 'طريقة إخفاء الهوية',
        'workflow_anonymize_action': 'إخفاء الهوية',
        'workflow_consent_title': 'الموافقة على إرسال البيانات',
        'workflow_consent_intro': 'يرجى مراجعة الشروط قبل إرسال أي بيانات إلى المنصة.',
        'workflow_consent_body': 'بإرسال البيانات، تؤكد ملكيتك لها وموافقتك على استخدامها ضمن أهداف المنصة.',
        'workflow_consent_agree': 'أوافق',
        'workflow_send': 'إرسال',
        'workflow_waiting': 'بانتظار البدء ...',
        'workflow_verify': 'يرجى تأكيد موافقتك على إرسال مجموعة البيانات.',
        'workflow_choose_file': 'يرجى اختيار ملف.',
        'workflow_upload_failed': 'فشل التحميل.',
        'workflow_upload_complete': 'تم حفظ الملف والبيانات الوصفية بنجاح.',
        'workflow_uploading': 'جارٍ التحميل ...',
        'workflow_upload_starting': 'بدء التحميل ...',
        'workflow_lang_en': 'الإنجليزية', 'workflow_lang_fa': 'الفارسية', 'workflow_lang_ar': 'العربية',
        'workflow_format_text': 'نص', 'workflow_format_image': 'صورة', 'workflow_format_sound': 'صوت',
        'workflow_no': 'لا', 'workflow_yes': 'نعم', 'workflow_number': 'رقم',
        'workflow_stage_basics': 'الأساسيات', 'workflow_stage_files': 'الملفات', 'workflow_stage_transfer': 'الرفع', 'workflow_stage_inspect': 'المراجعة', 'workflow_stage_access': 'الوصول والنشر',
        'quality_report': 'تقرير الجودة', 'quality_status': 'حالة المعالجة', 'quality_score': 'درجة الجودة', 'quality_assets': 'الأصول المفحوصة', 'quality_findings': 'النتائج', 'quality_publish': 'الموافقة والنشر', 'quality_publish_help': 'راجع التقرير قبل نشر هذه النسخة.', 'quality_processing': 'قيد المعالجة', 'quality_review': 'بحاجة إلى مراجعة', 'quality_failed': 'فشل', 'quality_image_count': 'الصور', 'quality_corrupt': 'الصور التالفة', 'quality_duplicates': 'الصور المكررة', 'quality_normalized': 'المخرج الموحّد',
        'workflow_basics_help': 'أدخل معلومات المجموعة مرة واحدة لتبقى مرتبطة بكل الملفات.', 'workflow_files_help': 'أضف ملفاً واحداً أو ملفات متعددة أو مجلداً أو أرشيف صور مضغوطاً.', 'workflow_transfer_help': 'يتم الرفع على أجزاء ويمكن استكماله للملفات الكبيرة.', 'workflow_inspect_help': 'راجع قائمة الملفات وانتظر فحوص الجودة الآلية.', 'workflow_access_help': 'اختر سياسة الوصول وأكد ملكية البيانات قبل النشر.',
        'workflow_choose_files': 'اختيار الملفات', 'workflow_choose_folder': 'اختيار مجلد', 'workflow_selected_files': 'الملفات المختارة', 'workflow_total_size': 'الحجم الإجمالي', 'workflow_remove': 'إزالة', 'workflow_start_upload': 'بدء الرفع', 'workflow_upload_queue': 'قائمة الرفع', 'workflow_archive': 'أرشيف مضغوط', 'workflow_file_manifest': 'قائمة الملفات', 'workflow_inspection_pending': 'تبدأ المراجعة بعد اكتمال رفع الملفات.', 'workflow_access_title': 'الوصول والنشر', 'workflow_publish_note': 'ستبقى المجموعة في الحجر حتى اكتمال الفحوص الآلية.', 'workflow_choose_files_first': 'اختر ملفاً أو مجلداً واحداً على الأقل.', 'workflow_upload_started': 'بدأ الرفع', 'workflow_upload_batch_complete': 'اكتمل رفع الملفات؛ فحوص الجودة قيد المعالجة.', 'workflow_load_file_help': 'اختر ملفاً منظماً بصيغة CSV أو TSV أو Excel. يتم تحليل الملف محلياً في المتصفح قبل الرفع.', 'workflow_file_formats': 'ملفات CSV/TSV وExcel حتى ٥٠ ميغابايت', 'workflow_local_profile': 'تحليل محلي', 'workflow_policy_help': 'راجع النوع المكتشف واختر إجراء حماية لكل عمود. يجب ألا تبقى أعمدة التعريف الحساسة دون حماية.', 'workflow_privacy_policy_help': 'تُخفى الكيانات النصية، وتُقرّب الأرقام أو تُجمع في نطاقات، وتُختزل التواريخ إلى السنة.', 'workflow_preview_help': 'راجع العينة المعالجة قبل رفعها. لا يتم إرسال الملف المحلي الأصلي.', 'workflow_confirmation_help': 'راجع إعدادات الوصول وأكد ملكية البيانات قبل رفع مجموعة البيانات المنقاة.', 'workflow_calculated_from_file': 'محسوب من الملف', 'workflow_sanitized_csv': 'CSV منقّى', 'workflow_changes_saved': 'تم حفظ طرق حماية الأعمدة بنجاح.', 'workflow_deidentification_complete': 'اكتمل إخفاء الهوية بنجاح. راجع المعاينة.',
        'workflow_none': 'بدون إخفاء الهوية', 'workflow_ner': 'التعرف على الكيانات (NER)', 'workflow_round': 'تقريب الأرقام', 'workflow_bin': 'تجميع ضمن نطاقات', 'workflow_year': 'الاحتفاظ بالسنة فقط', 'workflow_mask': 'استبدال برمز', 'workflow_privacy_warning': 'يجب اختيار طريقة حماية للأعمدة الحساسة.', 'workflow_transform_summary': 'اكتملت المعالجة', 'workflow_residual_pii': 'قد تبقى بيانات شخصية؛ راجعها قبل النشر.', 'workflow_no_residual_pii': 'لم يتم العثور على إشارات شائعة للبيانات الشخصية في العينة.', 'workflow_file_too_large': 'يدعم هذا المسار المحلي ملفات حتى ٥٠ ميغابايت.', 'workflow_excel_unavailable': 'دعم Excel غير متاح؛ اختر ملف CSV.', 'workflow_profile_failed': 'تعذر إنشاء ملف تعريف للبيانات.', 'workflow_deidentification_required': 'شغّل معاينة إخفاء الهوية أولاً.', 'workflow_anonymization': 'إجراء الخصوصية', 'workflow_confidence': 'ثقة الاكتشاف', 'workflow_data_type': 'نوع البيانات',
        'workflow_mean': 'المتوسط', 'workflow_median': 'الوسيط', 'workflow_min': 'الحد الأدنى', 'workflow_max': 'الحد الأقصى',
        'workflow_export': 'تصدير CSV', 'workflow_select_all': 'تحديد الكل', 'workflow_select_none': 'إلغاء التحديد', 'workflow_no_rows': 'الملف المحدد لا يحتوي على صفوف بيانات.',
        'team': 'فريقنا',
        'faq': 'الأسئلة الشائعة',
        'contact': 'اتصل بنا',
        'login_register': 'تسجيل الدخول / التسجيل',
        'profile': 'ملفي الشخصي',
        'account': 'الحساب',
        'my_datasets': 'مجموعات بياناتي',
        'my_products': 'منتجاتي',
        'requests': 'إدارة الطلبات',
        'logout': 'تسجيل الخروج',
        'language': 'اللغة',
        'search_datasets': 'البحث عن مجموعات البيانات',
        'search_help': 'اعثر على مجموعة البيانات المطلوبة باستخدام الكلمات المفتاحية',
        'search_placeholder': 'أدخل عبارة البحث',
        'unknown_publisher': 'ناشر غير معروف',
        'created': 'تاريخ الإنشاء',
        'records': 'السجلات',
        'free': 'مجاني',
        'currency': 'تومان',
        'view_dataset': 'عرض مجموعة البيانات',
        'no_datasets': 'لم يتم العثور على مجموعات بيانات',
        'change_search': 'غيّر عبارة البحث أو حاول مرة أخرى لاحقاً.',
        'description': 'الوصف',
        'structure': 'هيكل مجموعة البيانات',
        'comments': 'تعليقات المستخدمين',
        'technical_details': 'المواصفات التقنية',
        'related_products': 'المنتجات ذات الصلة',
        'likes': 'الإعجابات',
        'files': 'الملفات',
        'size': 'الحجم',
        'no_description': 'لا يوجد وصف لمجموعة البيانات هذه.',
        'no_structure': 'لا تتوفر معلومات عن الهيكل.',
        'no_comments': 'لا توجد تعليقات بعد.',
        'download_dataset': 'تنزيل / شراء مجموعة البيانات',
        'request_dataset': 'طلب الوصول / الشراء',
        'like_action': 'إعجاب',
        'share': 'مشاركة', 'share_telegram': 'Telegram', 'share_whatsapp': 'واتساب', 'share_twitter': 'X / Twitter', 'copy_link': 'نسخ الرابط', 'link_copied': 'تم نسخ الرابط بنجاح.', 'link_copy_failed': 'تعذر نسخ الرابط. يرجى نسخه يدويًا.',
        'view_metadata': 'عرض البيانات الوصفية',
        'similar': 'مجموعات بيانات مشابهة',
        'papers': 'الأبحاث',
        'models': 'النماذج',
        'services': 'الخدمات',
        'comment_placeholder': 'اكتب تعليقاً...',
        'send_comment': 'إرسال التعليق',
        'reference_link': 'الرابط المرجعي',
        'format': 'التنسيق',
        'language_label': 'اللغة',
        'license': 'الترخيص',
        'platform_tagline': 'سوق احترافي لاكتشاف وتبادل البيانات',
        'platform_intro': 'اعثر على مجموعات البيانات وشارك أعمالك وتعاون مع مجتمع البيانات.',
        'browse_datasets': 'تصفح مجموعات البيانات',
        'get_started': 'ابدأ الآن',
        'dataset_count': 'مجموعات البيانات',
        'user_count': 'المستخدمون النشطون',
        'request_count': 'الطلبات المقبولة',
        'footer_provided_by': 'مقدمة من',
        'home_eyebrow': 'بنية بيانات للعمل الحقيقي',
        'home_title': 'عالم البيانات بلا حدود',
        'home_intro': 'مستودع لتخزين مجموعات البيانات وتبادلها ومشاركتها، مخصص لمتخصصي الذكاء الاصطناعي.',
        'home_primary': 'تصفح البيانات',
        'home_secondary': 'إضافة مجموعة بيانات',
        'home_trust': 'مسار واضح نحو بيانات قابلة للاستخدام',
        'home_nav_workflow': 'طريقة العمل',
        'home_nav_integrations': 'التكاملات',
        'home_nav_start': 'ابدأ الآن',
        'home_workflow_eyebrow': 'كيف تعمل المنصة',
        'home_workflow_title': 'من الملفات الخام إلى مجموعة بيانات موثوقة',
        'home_workflow_intro': 'اجعل كل خطوة ضمن مسار واحد واضح بدلاً من استخدام أدوات متفرقة.',
        'home_step_1': 'اكتشف أو أضف',
        'home_step_1_text': 'ابحث في كتالوج DataHub أو أضف ملفاتك ومجلداتك.',
        'home_step_2': 'الوصف والحماية',
        'home_step_2_text': 'راجع البيانات الوصفية والوسوم وإجراءات الخصوصية قبل الرفع.',
        'home_step_3': 'فحص الجودة',
        'home_step_3_text': 'افحص بنية الملفات والعينات وإشارات البيانات الشخصية تلقائياً.',
        'home_step_4': 'النشر والتبادل',
        'home_step_4_text': 'بعد المراجعة، شارك البيانات بشكل خاص أو مجاناً أو عبر السوق.',
        'home_capabilities_eyebrow': 'مصمم لفرق البيانات',
        'home_capabilities_title': 'كل ما تحتاجه مجموعة البيانات الاحترافية',
        'home_capabilities_intro': 'احتفظ بالبيانات الوصفية والملفات وحالة المعالجة في مكان واحد.',
        'home_capability_discover': 'اكتشاف سريع',
        'home_capability_discover_text': 'استخدم البيانات الوصفية والوسوم للعثور على المجموعة المناسبة بسرعة.',
        'home_capability_prepare': 'إعداد آمن',
        'home_capability_prepare_text': 'جهّز الملفات الكبيرة والأرشيفات والبيانات المنظمة مع فحوص واضحة.',
        'home_capability_exchange': 'سوق البيانات',
        'home_capability_exchange_text': 'تحكم في الوصول والسعر وشروط الاستخدام عند تبادل البيانات.',
        'home_integrations_title': 'اتصل بالمصادر الموثوقة',
        'home_integrations_text': 'اجلب بيانات Hugging Face وKaggle الوصفية وأدرها في DataHub.',
        'home_privacy_title': 'الخصوصية جزء من سير العمل',
        'home_privacy_text': 'يساعدك التحليل المحلي واكتشاف الأعمدة الحساسة وفحوص الجودة على اتخاذ قرار واثق قبل النشر.',
        'home_privacy_action': 'جهّز مجموعة بيانات',
        'home_faq_eyebrow': 'الدليل',
        'home_faq_title': 'الأسئلة الشائعة',
        'home_faq_intro': 'إجابات قصيرة لمساعدتك على بدء استخدام DataHub.',
        'home_faq_q1': 'ما أنواع الملفات التي يمكنني إضافتها؟',
        'home_faq_a1': 'يمكنك إضافة ملف واحد أو عدة ملفات أو مجلد أو أرشيف مضغوط مثل ZIP.',
        'home_faq_q2': 'هل يتم فحص البيانات قبل النشر؟',
        'home_faq_a2': 'نعم. يتم فحص الجودة وبنية الملفات وإشارات البيانات الشخصية وتسجيل النتائج للمراجعة.',
        'home_faq_q3': 'هل يمكنني الاستيراد من Kaggle أو Hugging Face؟',
        'home_faq_a3': 'نعم. أدخل معرّف مجموعة البيانات ليتم جلب البيانات الوصفية والملفات بشكل آمن.',
        'home_faq_q4': 'متى يمكن للمستخدمين الآخرين رؤية بياناتي؟',
        'home_faq_a4': 'تبقى المجموعة في المسودة أو الحجر حتى تقوم بمراجعتها ونشرها.',
        'home_cta_title': 'جهّز مجموعة بيانات مشروعك القادمة',
        'home_cta_text': 'تصفح البيانات المتاحة أو أضف أول مجموعة بيانات إلى DataHub اليوم.',
        'home_cta_action': 'ابدأ الآن',
    },
}


def ui(request):
    language = (get_language() or 'fa').split('-')[0]
    return {
        'ui': UI_TEXT.get(language, UI_TEXT['en']),
        'current_language': language,
        'is_rtl': language in {'fa', 'ar'},
    }
