# Generated by Django 5.2.4 on 2026-09-30 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0008_datasetversion_published_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('access_model', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('request', 'Request approval')], default='paid', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount_minor', models.PositiveBigIntegerField(default=0)),
                ('terms_version', models.CharField(default='1', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='listing', to='dataset.datasetversion')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_entitlements', to=settings.AUTH_USER_MODEL)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='dataset.datasetversion')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement', to='marketplace.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('buyer', 'dataset_version'), name='unique_buyer_dataset_entitlement')],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('provider_event_id', models.CharField(max_length=180)),
                ('status', models.CharField(max_length=30)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='marketplace.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_payment_provider_event')],
            },
        ),
    ]
