# Generated by Django 5.2.4 on 2026-10-04 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderImportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_job_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('request_key', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('huggingface', 'Hugging Face'), ('kaggle', 'Kaggle')], max_length=20)),
                ('provider_dataset_id', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='queued', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('gui_dataset_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gui_dataset_version_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_import_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_provider_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='dashboard_p_status_395a14_idx'), models.Index(fields=['provider', 'created_at'], name='dashboard_p_provide_ec3682_idx')],
            },
        ),
    ]
